Repository zeit-ui/vue, pull requests merged in 2019-06, with the labels that each got.

#60 fix(radio): modify radio style
  docs/en-us/components/dialog.md
  docs/en-us/components/popover.md
  docs/en-us/components/radio.md
  docs/en-us/components/select.md
  docs/en-us/components/switcher.md
  docs/en-us/components/toggle.md
  docs/examples/collapse/basic.vue
  docs/examples/dialog/more.vue
  docs/examples/radio/basic.vue
  docs/examples/radio/disabled.vue
  docs/examples/radio/group.vue
  examples/umd/index.html
  package.json
  packages/dialog/dialog.styl
  packages/dialog/dialog.vue
  packages/radio/radio.vue
  src/components/blocks/side.styl
Labels: bug

#61 feat(switcher): upgrade interfaces
  docs/en-us/components/switcher.md
  docs/examples/switcher/basic.vue
  docs/examples/switcher/multiple.vue
  package.json
  packages/switcher/index.js
  packages/switcher/switcher-item.vue
  packages/switcher/switcher.vue
Labels: feature, want merge

#62 fix switcher and format filename
  docs/examples/switcher/multiple.vue
  package.json
  packages/button/button-drip.vue
  packages/button/button.vue
  packages/checkbox/checkbox-group.vue
  packages/checkbox/index.js
  packages/collapse/collapse-item.vue
  packages/collapse/index.js
  packages/files/files-icon.vue
  packages/files/files-item.vue
  packages/files/files-status.vue
  packages/files/index.js
  packages/popover/index.js
  packages/popover/popover-item.vue
  packages/radio/index.js
  packages/radio/radio-group.vue
  packages/select/index.js
  packages/select/select-option.vue
  packages/switcher/switcher-item.vue
  packages/switcher/switcher.vue
Labels: want merge

#66 fix(main): fix typo
  src/main.js
Labels: bug, want merge

#68 fix(input): fix clearicon missing in dark mode
  packages/input/input.vue
Labels: bug, need review, want merge

#69 fix(markdown): fix color of code
  .github/ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE/1-bug-report.md
  .github/ISSUE_TEMPLATE/2-feature-request.md
  .github/ISSUE_TEMPLATE/3-styles.md
  .github/ISSUE_TEMPLATE/4-docs.md
  src/assets/styles/index.styl
  src/assets/styles/prism-ghcolors.styl
  src/components/examples/code.styl
  src/components/examples/code.vue
  vue.config.js
Labels: bug, docs, want merge

#65 feat(slider): add component & docs
  .gitignore
  docs/en-us/components/progress.md
  docs/en-us/components/slider.md
  docs/examples/link/more.vue
  docs/examples/note/type.vue
  docs/examples/progress/color.vue
  docs/examples/slider/basic.vue
  docs/examples/slider/step.vue
  package.json
  packages/index.js
  packages/note/note.vue
  packages/progress/progress.vue
  packages/slider/index.js
  packages/slider/slider.styl
  packages/slider/slider.vue
Labels: docs, need review, want merge

#71 fix: fix popover
  packages/popover/popover-icon.vue
  packages/popover/popover-item.vue
  packages/popover/popover.styl
  packages/popover/popover.vue
Labels: bug, want merge

#72 fix(files): fix color of the status icon
  packages/files/files-status.vue
Labels: bug, want merge

#77 docs: add nut showcase
  README.md
Labels: docs, want merge

#73 fix: optimize link style & add slider touch event
  packages/link/link.styl
  packages/link/link.vue
  packages/progress/progress.styl
  packages/slider/slider.vue
  packages/table/table.vue
Labels: feature, want merge

#78 fix(slider): add railWidth listner
  docs/examples/slider/basic.vue
  docs/examples/slider/step.vue
  packages/slider/slider.styl
  packages/slider/slider.vue
Labels: bug

#79 fix(popover): update theme when popover triggered
  packages/popover/popover-icon.vue
  packages/popover/popover.vue
Labels: bug, want merge
