Repository zeit-ui/vue, pull requests merged in 2019-07, with the labels that each got.

#86 feat: v2
  docs/en-us/components/avatar.md
  docs/en-us/components/badge.md
  docs/en-us/components/button.md
  docs/en-us/components/card.md
  docs/en-us/components/checkbox.md
  docs/en-us/components/code.md
  docs/en-us/components/collapse.md
  docs/en-us/components/dialog.md
  docs/en-us/components/fieldset.md
  docs/en-us/components/files.md
  docs/en-us/components/image.md
  docs/en-us/components/input.md
  docs/en-us/components/link.md
  docs/en-us/components/more.md
  docs/en-us/components/note.md
  docs/en-us/components/popover.md
  docs/en-us/components/progress.md
  docs/en-us/components/radio.md
  docs/en-us/components/rate.md
  docs/en-us/components/select.md
  docs/en-us/components/slider.md
  docs/en-us/components/spinner.md
  docs/en-us/components/switcher.md
  docs/en-us/components/table.md
  docs/en-us/components/tag.md
  docs/en-us/components/toast.md
  docs/en-us/components/toggle.md
  docs/examples/image/caption.vue
  docs/examples/image/static.vue
  docs/examples/progress/fixed.vue
  packages/image/image.vue
  packages/image/index.js
  packages/index.js
  src/components/examples/code.vue
Labels: docs, feature

#92 docs: update theme
  docs/en-us/start/theme.md
Labels: docs

#91 fix(radio): modify radio style
  docs/en-us/components/radio.md
  docs/examples/radio/basic.vue
  docs/examples/radio/disabled.vue
  docs/examples/radio/group.vue
  packages/radio/radio.styl
  packages/radio/radio.vue
Labels: need review

#94 feat: add layout component
  docs/en-us/components/layout.md
  docs/examples/layout/alignment.vue
  docs/examples/layout/basic.vue
  docs/examples/layout/column.vue
  docs/examples/layout/compose.vue
  docs/examples/layout/spacing.vue
  packages/col/col.styl
  packages/col/col.vue
  packages/col/index.js
  packages/index.js
  packages/row/index.js
  packages/row/row.vue
  src/components/examples/footer.vue
Labels: docs, feature, want merge

#96 fix(theme): fix global styles
  docs/en-us/start/theme.md
  package.json
  packages/utils/styles/layout.styl
  src/components/examples/code.vue
  src/components/examples/footer.vue
  yarn.lock
Labels: bug, want merge

#95 fix(slider): add disabled & slider's range
  docs/en-us/components/slider.md
  docs/examples/radio/group.vue
  docs/examples/slider/basic.vue
  docs/examples/slider/disabled.vue
  docs/examples/slider/range.vue
  docs/examples/slider/step.vue
  packages/radio/radio.styl
  packages/slider/slider.styl
  packages/slider/slider.vue
Labels: bug, docs, need review

#97 fix(note): modify note
  docs/en-us/components/note.md
  docs/examples/note/basic.vue
  docs/examples/note/filled.vue
  docs/examples/note/type.vue
  docs/examples/slider/range.vue
  packages/note/note.styl
  packages/note/note.vue
Labels: need review

#100 fix(switcher): fix style on actived
  docs/en-us/components/link.md
  docs/en-us/start/installation.md
  docs/examples/link/basic.vue
  docs/examples/link/more.vue
  docs/examples/link/to.vue
  packages/link/link-icon.vue
  packages/link/link.styl
  packages/link/link.vue
  packages/switcher/switcher.styl
Labels: enhancement, feature, want merge

#105 fix(toast): animation reference
  packages/toast/toast.styl
Labels: bug
