Repository zeit-ui/vue, pull requests merged in 2019-05, with the labels that each got.

#49 feat: improve the EX of mobile browsers
  public/index.html
  src/assets/fonts/iconfont.css
  src/assets/fonts/iconfont.eot
  src/assets/fonts/iconfont.svg
  src/assets/fonts/iconfont.ttf
  src/assets/fonts/iconfont.woff
  src/assets/fonts/iconfont.woff2
  src/assets/index.styl
  src/assets/styles/index.styl
  src/assets/styles/responsive.styl
  src/assets/styles/vars.styl
  src/components/blocks/side.styl
  src/components/blocks/side.vue
  src/components/examples/code_render.vue
  src/main.js
  src/pages/documents/slot.vue
  vue.config.js
Labels: feature, test passed, want merge

#50 fix: Typo inside handler.vue
  docs/examples/toast/handler.vue
Labels: bug, want merge

#51 docs: improve attribute docs
  docs/en-us/components/more.md
  docs/en-us/components/note.md
  docs/en-us/components/popover.md
  docs/en-us/components/progress.md
  docs/en-us/components/radio.md
  docs/en-us/components/rate.md
  docs/en-us/components/select.md
  docs/en-us/components/spinner.md
  docs/en-us/components/switcher.md
  docs/en-us/components/tag.md
  docs/en-us/components/toast.md
  docs/en-us/components/toggle.md
Labels: docs, enhancement, want merge

#52 docs: append showcase
  README.md
Labels: docs, want merge

#53 docs: add attribute docs
  docs/en-us/components/checkbox.md
  docs/en-us/components/popover.md
  docs/en-us/components/table.md
  docs/en-us/components/toggle.md
  docs/examples/table/basic.vue
  packages/progress/progress.vue
  packages/table/table-body.js
  packages/table/table-column.js
  packages/table/table-store.js
Labels: docs, need review

#55 fix(table): table style problem
  docs/examples/table/basic.vue
  packages/table/table.styl
  packages/table/table.vue
Labels: bug

#56 chore: release 0.6.0
  package.json
  yarn.lock
Labels: want merge

#57 style: format code style
  .eslintrc
  docs/examples/files/basic.vue
  docs/examples/index.js
  docs/examples/table/basic.vue
  docs/examples/table/width.vue
  docs/index.js
  package.json
  packages/avatar/avatar.vue
  packages/button/button_drip.vue
  packages/collapse/collapse.vue
  packages/collapse/collapse_item.vue
  packages/dialog/dialog.vue
  packages/files/files_item.vue
  packages/progress/progress.vue
  packages/switcher/switcher.vue
  packages/table/table-body.js
  packages/table/table-column.js
  packages/table/table-header.js
  packages/table/table-layout.js
  packages/table/table-store.js
  packages/table/table.vue
  packages/toast/service.js
  packages/toast/toast.vue
  packages/utils/bounding.js
  packages/utils/print.js
  packages/utils/transitions/expand.vue
  packages/utils/validator.js
  src/main.js
  src/pages/documents/index.vue
  yarn.lock
Labels: test passed, want merge

#58 fix: remove unused
  packages/link/link.vue
  packages/toast/service.js
Labels: bug, want merge

#59 fix: fix install on UMD mode
  docs/en-us/start/installation.md
  examples/umd/index.html
  packages/index.js
Labels: bug, want merge
