Repository zeit-ui/vue, pull requests merged in 2019-03, with the labels that each got.

#36 fix(switcher): fix props validate & adjust example
  docs/examples/switcher/basic.vue
  docs/examples/switcher/multiple.vue
  packages/switcher/switcher.vue
Labels: bug, need review, want merge

#37 feat(dialog): init component and examples
  docs/examples/dialog/baisc.vue
  docs/examples/dialog/custom.vue
  docs/examples/dialog/more.vue
  docs/zh-cn/components/dialog.md
  package.json
  packages/dialog/dialog.styl
  packages/dialog/dialog.vue
  packages/dialog/index.js
  packages/index.js
Labels: feature, want merge

#38 chore: release v0.4.2
  docs/examples/button/type.vue
  docs/examples/switcher/basic.vue
  docs/examples/switcher/multiple.vue
  package.json
  packages/switcher/switcher.vue
  yarn.lock
Labels: bug, want merge

#39 fix(code): remove unused code
  package.json
  packages/code/code.vue
  packages/popover/popover.styl
  packages/popover/popover.vue
  packages/popover/popover_item.vue
  yarn.lock
Labels: bug, want merge

#40 feat(progress): add progress component
  docs/examples/progress/basic.vue
  docs/examples/progress/color.vue
  docs/examples/progress/fixed.vue
  docs/zh-cn/components/progress.md
  package.json
  packages/index.js
  packages/progress/index.js
  packages/progress/progress.vue
  yarn.lock
Labels: need review, want merge

#41 fix(link): solve icon misalignment
  package.json
  packages/link/link.vue
Labels: bug

#43 feat(files): add component and examples
  docs/examples/files/basic.vue
  docs/zh-cn/components/files.md
  now.json
  package.json
  packages/files/files.vue
  packages/files/files_icon.vue
  packages/files/files_item.vue
  packages/files/files_status.vue
  packages/files/index.js
  packages/index.js
  public/favicon.ico
Labels: feature, want merge
