Repository zeit-ui/vue, pull requests merged in 2019-02, with the labels that each got.

#1 ci: add configs for ci
  .circleci/config.yml
  .commitlintrc.yml
  .github/CONTRIBUTING.md
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
  .travis.yml
  package-lock.json
  package.json
Labels: feature, want merge

#2 fix: solve lint warning
  .eslintrc
  docs/examples/checkbox/group.vue
  package.json
  packages/button/button_drip.vue
Labels: bug, test passed, want merge

#3 feat(input): add component and examples
  docs/examples/input/basic.vue
  docs/examples/input/clearable.vue
  docs/examples/input/disabled.vue
  docs/examples/input/label.vue
  docs/examples/input/size.vue
  docs/zh-cn/components/input.md
  package-lock.json
  package.json
  packages/index.js
  packages/input/index.js
  packages/input/input.vue
Labels: feature, want merge

#5 docs(readme): add logo
  README.md
  public/index.html
Labels: docs, want merge

#7 feat(select): add component and examples
  docs/examples/footnote/target.vue
  docs/examples/select/basic.vue
  docs/examples/select/disabled.vue
  docs/examples/select/simple.vue
  docs/examples/select/size.vue
  docs/zh-cn/components/select.md
  package-lock.json
  package.json
  packages/index.js
  packages/input/input.vue
  packages/select/index.js
  packages/select/select.vue
  packages/select/select_option.vue
Labels: feature, test passed, want merge

#9 feat(more): add component and examples
  docs/examples/more/basic.vue
  docs/examples/more/default.vue
  docs/examples/more/loading.vue
  docs/zh-cn/components/more.md
  package-lock.json
  package.json
  packages/index.js
  packages/more/index.js
  packages/more/more.vue
Labels: feature, need review, want merge

#11 ci(auto_assign): auto assign when review approve
  .github/auto_assign.yml
  now.json
Labels: feature, want merge

#10 feat(toggle): add component and examples
  docs/examples/toggle/basic.vue
  docs/examples/toggle/disabled.vue
  docs/zh-cn/components/toggle.md
  packages/index.js
  packages/toggle/index.js
  packages/toggle/toggle.vue
Labels: feature, want merge

#12 ci: remove auto assign
  .github/auto_assign.yml
Labels: want merge

#17 chore: migrate to vue 2.6
  docs/examples/fieldset/custom.vue
  docs/examples/fieldset/disabled.vue
  package-lock.json
  package.json
Labels: enhancement, want merge

#14 feat(switcher): component and examples
  docs/examples/switcher/basic.vue
  docs/examples/switcher/multiple.vue
  docs/zh-cn/components/switcher.md
  packages/index.js
  packages/switcher/index.js
  packages/switcher/switcher.vue
Labels: need review, want merge

#19 feat(rate): add component and examples
  docs/examples/rate/basic.vue
  docs/examples/rate/disabled.vue
  docs/zh-cn/components/rate.md
  package-lock.json
  package.json
  packages/index.js
  packages/rate/index.js
  packages/rate/rate.vue
Labels: feature, want merge

#20 fix: fix doc module match
  src/components/doc.vue
Labels: bug, want merge

#21 feat(tag): component and example
  docs/examples/tag/basic.vue
  docs/zh-cn/components/tag.md
  packages/index.js
  packages/tag/index.js
  packages/tag/tag.vue
Labels: feature, want merge

#22 fix(tag example): fix style
  docs/examples/tag/basic.vue
Labels: bug, want merge

#23 feat(toast): add component and examples
  docs/examples/button/ghost.vue
  docs/examples/toast/action.vue
  docs/examples/toast/basic.vue
  docs/examples/toast/duration.vue
  docs/examples/toast/handler.vue
  docs/examples/toast/status.vue
  docs/zh-cn/components/button.md
  docs/zh-cn/components/toast.md
  package-lock.json
  package.json
  packages/button/button.vue
  packages/button/button_drip.vue
  packages/index.js
  packages/toast/index.js
  packages/toast/service.js
  packages/toast/toast.vue
  packages/utils/bounding.js
Labels: feature, want merge

#24 chore: add license file
  LICENSE
Labels: enhancement, want merge

#16 feat(note): component and examples
  docs/examples/note/basic.vue
  docs/examples/note/type.vue
  docs/examples/tag/basic.vue
  docs/zh-cn/components/note.md
  docs/zh-cn/components/tag.md
  package-lock.json
  packages/index.js
  packages/note/index.js
  packages/note/note.vue
  packages/tag/tag.vue
Labels: feature

#25 feat(spinner): add component and examples
  docs/examples/spinner/basic.vue
  docs/examples/spinner/size.vue
  docs/zh-cn/components/spinner.md
  package-lock.json
  package.json
  packages/index.js
  packages/spinner/index.js
  packages/spinner/spinner.vue
Labels: feature, want merge

#27 feat: improve example and docs
  docs/zh-cn/start/about.md
  docs/zh-cn/start/installation.md
  package-lock.json
  package.json
  src/assets/fonts/iconfont.css
  src/assets/fonts/iconfont.eot
  src/assets/fonts/iconfont.svg
  src/assets/fonts/iconfont.ttf
  src/assets/fonts/iconfont.woff
  src/assets/fonts/iconfont.woff2
  src/assets/fonts/index.styl
  src/assets/index.styl
  src/components/blocks/side.vue
  src/components/examples/code.vue
  src/main.js
  src/pages/documents/slot.vue
  yarn.lock
Labels: feature, want merge

#28 feat: popover component
  .circleci/config.yml
  .travis.yml
  docs/examples/popover/align.vue
  docs/examples/popover/basic.vue
  docs/examples/popover/command.vue
  docs/examples/popover/split.vue
  docs/zh-cn/components/popover.md
  package.json
  packages/index.js
  packages/popover/index.js
  packages/popover/popover.vue
  packages/popover/popover_item.vue
  yarn.lock
Labels: feature, need review, want merge

#30 docs: update import guide for style
  README.md
  docs/zh-cn/start/installation.md
Labels: docs, want merge

#31 fix: add medium to size prop
  docs/examples/avatar/size.vue
  package.json
  packages/avatar/avatar.vue
Labels: bug, want merge

#32 fix(radio): add radio component and doc
  docs/examples/radio/basic.vue
  docs/examples/radio/disabled.vue
  docs/examples/radio/group.vue
  docs/zh-cn/components/radio.md
  package.json
  packages/avatar/avatar.vue
  packages/index.js
  packages/radio/index.js
  packages/radio/radio.vue
  packages/radio/radio_group.vue
  packages/toast/service.js
Labels: feature, want merge

#33 chore(pkg): release v0.2
  docs/examples/card/hoverable.vue
  docs/examples/card/pin.vue
  docs/zh-cn/components/card.md
  package.json
  packages/card/card.vue
  yarn.lock
Labels: feature, want merge

#34 feat(link): init component and examples
  docs/examples/link/basic.vue
  docs/examples/link/more.vue
  docs/examples/link/style.vue
  docs/examples/link/to.vue
  docs/zh-cn/components/link.md
  package.json
  packages/index.js
  packages/link/index.js
  packages/link/link.vue
Labels: feature, want merge

#35 docs: update docs about style
  README.md
  docs/zh-cn/start/installation.md
  package.json
  packages/index.js
  packages/link/link.vue
  packages/style.css
  src/main.js
Labels: bug, docs, want merge
