Repository zeit-ui/vue, pull requests merged in 2020-03, with the labels that each got.

#142 docs(badge): fix typo
  docs/zh-cn/components/badge.md
Labels: docs

#144 fix(note): fix inaccurate naming on props
  docs/en-us/components/note.md
  docs/examples/note/filled.vue
  docs/examples/note/type.vue
  docs/zh-cn/components/note.md
  packages/note/note.styl
  packages/note/note.vue
Labels: bug

#146 fix(dialog): fix external model is ignored when component mounted
  packages/dialog/dialog.vue
Labels: bug

#147 feat(tabs): add component
  docs/en-us/components/tabs.md
  docs/examples/switcher/multiple.vue
  docs/examples/tabs/basic.vue
  docs/examples/tabs/disabled.vue
  docs/examples/tabs/icon.vue
  docs/zh-cn/components/switcher.md
  docs/zh-cn/components/tabs.md
  packages/index.js
  packages/tabs/index.js
  packages/tabs/tabs-item.vue
  packages/tabs/tabs.styl
  packages/tabs/tabs.vue
Labels: feature

#148 fix(tabs): fix styles of mouse pointer
  docs/en-us/components/tabs.md
  docs/zh-cn/components/tabs.md
  packages/tabs/tabs.styl
Labels: bug, need review

#149 fix: the button component computed `classes` invoke trim
  packages/button/button.vue
Labels: bug

#151 Remove uesless code
  packages/button/button.vue
Labels: styles, want merge

#156 fix(rate): optimize the display of icon
  packages/rate/rate-icon.vue
  packages/rate/rate.styl
  packages/rate/rate.vue
  src/components/examples/footer.vue
Labels: bug

#157 fix: improve spacing of multiple components
  package.json
  packages/code/code.styl
  packages/fieldset/fieldset.styl
  src/pages/documents/document-slot.vue
  yarn.lock
Labels: bug

#158 Fix the input component
  packages/input/input.vue
Labels: bug

#159 Fix the toast
  packages/toast/service.js
  packages/toast/toast.styl
Labels: bug

#164 docs: improve scrollbar on windows
  src/app.vue
  src/components/blocks/side.styl
Labels: docs

#163 fix(button): add icon model
  docs/en-us/components/button.md
  docs/examples/button/custom-icon.vue
  docs/examples/button/icon.vue
  docs/zh-cn/components/button.md
  packages/button/button.styl
  packages/button/button.vue
Labels: want merge

#168 docs: fix Chinese translation
  docs/zh-cn/customization/colors.md
Labels: docs
