Repository zeit-ui/vue, pull requests merged in 2020-02, with the labels that each got.

#124 feat: add textarea
  docs/en-us/components/textarea.md
  docs/examples/textarea/basic.vue
  docs/examples/textarea/disabled.vue
  docs/examples/textarea/type.vue
  packages/index.js
  packages/textarea/index.js
  packages/textarea/textarea.styl
  packages/textarea/textarea.vue
Labels: feature, need review

#125 chore: remove outdated case
  README.md
Labels: docs

#126 fix: card&layout&avatar add $listeners
  packages/avatar/avatar.vue
  packages/card/card.vue
  packages/col/col.vue
  packages/row/row.vue
Labels: bug

#127 feat(link): improve component to follow new design
  docs/examples/link/basic.vue
  package.json
  packages/link/link-icon.vue
  packages/link/link.styl
  packages/link/link.vue
  yarn.lock
Labels: dependencies, feature

#128 feat(note): improve component to follow new design
  docs/en-us/components/note.md
  packages/note/note.styl
  packages/note/note.vue
Labels: enhancement

#129 fix: add input type & event
  docs/en-us/components/input.md
  docs/examples/input/type.vue
  packages/input/input.styl
  packages/input/input.vue
Labels: enhancement

#130 feat(input): support for external icons
  docs/en-us/components/input.md
  docs/examples/input/icon.vue
  package.json
  packages/input/input.styl
  packages/input/input.vue
  src/components/examples/code.vue
  yarn.lock
Labels: enhancement

#131 fix(toggle): upgrade style
  packages/toggle/toggle.styl
Labels: enhancement

#132 feat(image): add shadow style
  docs/en-us/components/image.md
  docs/en-us/start/installation.md
  docs/en-us/start/theme.md
  docs/examples/image/shadow.vue
  packages/image/image.vue
Labels: feature

#133 feat(dot): add component & style
  docs/en-us/components/dot.md
  docs/examples/dot/basic.vue
  docs/examples/dot/label.vue
  packages/dot/dot.styl
  packages/dot/dot.vue
  packages/dot/index.js
  packages/index.js
Labels: feature

#134 feat(spacer): add component & style
  docs/en-us/components/spacer.md
  docs/examples/spacer/horizontal.vue
  docs/examples/spacer/vertical.vue
  packages/index.js
  packages/spacer/index.js
  packages/spacer/spacer.styl
  packages/spacer/spacer.vue
Labels: feature

#135 docs: improve the visual effects of document site
  docs/en-us/customization/colors.md
  docs/en-us/customization/icons.md
  docs/en-us/customization/themes.md
  docs/en-us/customization/typography.md
  docs/en-us/getting-started/installation.md
  docs/en-us/getting-started/introduction.md
  docs/en-us/start/theme.md
  docs/examples/color/_mixin.js
  docs/examples/color/color.styl
  docs/examples/color/color.vue
  docs/examples/color/error.vue
  docs/examples/color/highlight.vue
  docs/examples/color/success.vue
  docs/examples/color/warning.vue
  docs/examples/typography/headings.vue
  docs/examples/typography/list.vue
  docs/examples/typography/paragraph.vue
  docs/examples/typography/small.vue
  package.json
  src/components/blocks/side.vue
  src/components/blocks/widgets.vue
  src/components/doc.vue
  src/components/examples/code.vue
  src/components/exhibits.vue
  src/pages/documents/document-main.vue
  src/pages/documents/document-slot.vue
  yarn.lock
Labels: docs, enhancement

#136 docs: support chinese
  README.md
  docs/en-us/components/badge.md
  docs/index.js
  docs/zh-cn/components/avatar.md
  docs/zh-cn/components/badge.md
  docs/zh-cn/components/button.md
  docs/zh-cn/components/card.md
  docs/zh-cn/components/checkbox.md
  docs/zh-cn/components/code.md
  docs/zh-cn/components/collapse.md
  docs/zh-cn/components/description.md
  docs/zh-cn/components/dialog.md
  docs/zh-cn/components/dot.md
  docs/zh-cn/components/fieldset.md
  docs/zh-cn/components/files.md
  docs/zh-cn/components/image.md
  docs/zh-cn/components/input.md
  docs/zh-cn/components/keyboard.md
  docs/zh-cn/components/layout.md
  docs/zh-cn/components/link.md
  docs/zh-cn/components/more.md
  docs/zh-cn/components/note.md
  docs/zh-cn/components/popover.md
  docs/zh-cn/components/progress.md
  docs/zh-cn/components/radio.md
  docs/zh-cn/components/rate.md
  docs/zh-cn/components/select.md
  docs/zh-cn/components/slider.md
  docs/zh-cn/components/spacer.md
  docs/zh-cn/components/spinner.md
  docs/zh-cn/components/switcher.md
  docs/zh-cn/components/table.md
  docs/zh-cn/components/tag.md
  docs/zh-cn/components/textarea.md
  docs/zh-cn/components/toast.md
  docs/zh-cn/components/toggle.md
  docs/zh-cn/components/tooltip.md
  docs/zh-cn/customization/colors.md
  docs/zh-cn/customization/icons.md
  docs/zh-cn/customization/themes.md
  docs/zh-cn/customization/typography.md
  docs/zh-cn/getting-started/installation.md
  docs/zh-cn/getting-started/introduction.md
  src/app.vue
  src/components/blocks/side.vue
  src/components/blocks/side.zh-cn.js
  src/components/blocks/widgets.vue
  src/components/doc.vue
  src/pages/documents/document-main.vue
  src/router.js
Labels: docs

#137 docs: fix multiple routes error on page reload
  src/app.vue
  src/router.js
Labels: bug, docs
