Repository zeit-ui/vue, pull requests merged in 2020-07, with the labels that each got.

#196 fix(dialog): fix the problem about scrollbar
  docs/examples/snippet/basic.vue
  packages/dialog/dialog.styl
  packages/select/down-icon.vue
  packages/utils/bodyScroll.js
  packages/utils/validator.js
  src/app.vue
  src/components/examples/arrow-icon.vue
Labels: bug

#201 feat(grid): add function of hide grid item
  docs/en-us/components/grid.md
  docs/examples/grid/hidden.vue
  docs/zh-cn/components/grid.md
  packages/grid/grid.vue
  src/components/blocks/side.vue
Labels: feature

#202 chore: delete vue-clipboard2
  package.json
  src/components/blocks/side.styl
  src/components/examples/code.vue
  src/main.js
  yarn.lock
Labels: chore

#207 Changed toggle background from fixed color to CSS variable
  packages/toggle/toggle.styl
Labels: chore
