Repository zeit-ui/vue, pull requests merged in 2020-04, with the labels that each got.

#172 fix(collapse): add model & update style
  docs/en-us/components/collapse.md
  docs/examples/collapse/shadow.vue
  docs/examples/collapse/subtitle.vue
  docs/zh-cn/components/collapse.md
  packages/collapse/collapse-item.vue
  packages/collapse/collapse.styl
  packages/progress/progress.vue
Labels: styles

#173 feat(display): add component
  docs/en-us/components/display.md
  docs/en-us/components/image.md
  docs/examples/collapse/subtitle.vue
  docs/examples/display/basic.vue
  docs/examples/display/caption.vue
  docs/examples/display/width.vue
  docs/examples/image/caption.vue
  docs/examples/image/shadow.vue
  docs/zh-cn/components/display.md
  docs/zh-cn/components/image.md
  packages/display/display.styl
  packages/display/display.vue
  packages/display/index.js
  packages/image/image.vue
  packages/index.js
  public/examples/github-comment.png
  public/examples/redirecting-domains.png
Labels: feature

#175 chore(examples): add example for nuxtjs
  examples/with-nuxtjs/README.md
  examples/with-nuxtjs/assets/.gitkeep
  examples/with-nuxtjs/css/main.css
  examples/with-nuxtjs/nuxt.config.js
  examples/with-nuxtjs/package.json
  examples/with-nuxtjs/pages/about.vue
  examples/with-nuxtjs/pages/index.vue
  examples/with-nuxtjs/plugins/theme.js
  examples/with-nuxtjs/yarn.lock
Labels: chore

#176 chore: upgrade deps
  package.json
  yarn.lock
Labels: chore
