Repository zeit-ui/vue, pull requests merged in 2020-06, with the labels that each got.

#181 feat(user): add component & doc
  docs/en-us/components/display.md
  docs/en-us/components/user.md
  docs/examples/user/basic.vue
  docs/examples/user/description.vue
  docs/examples/user/social.vue
  docs/zh-cn/components/display.md
  docs/zh-cn/components/user.md
  packages/avatar/avatar.vue
  packages/index.js
  packages/user/index.js
  packages/user/user.styl
  packages/user/user.vue
Labels: feature

#185 Made toast full width by default
  packages/toast/toast.styl
  packages/toast/toast.vue
Labels: bug

#188 docs: fix touch event on firefox
  src/components/blocks/side.styl
  src/components/blocks/side.vue
Labels: bug, docs

#190 feat(tooltip): upgrade popover to v2
  package.json
  packages/tooltip/tooltip.styl
  packages/tooltip/tooltip.vue
  yarn.lock
Labels: feature, test passed

#191 fix(button): add style for tab selected & update style bug
  docs/examples/button/basic.vue
  packages/button/button.styl
  packages/button/button.vue
Labels: bug

#192 fix: update code/fieldset/collapse/code styles problem & image address
  docs/examples/display/basic.vue
  docs/examples/image/static.vue
  packages/collapse/collapse.styl
  packages/fieldset/fieldset.styl
  public/examples/vue-zeit.png
  src/components/blocks/side.styl
  src/components/blocks/side.vue
  src/components/examples/code.vue
Labels: bug, styles

#193 feat: add bodyScroll function
  packages/dialog/dialog.vue
  packages/fieldset/fieldset.styl
  packages/utils/bodyScroll.js
  packages/utils/index.js
Labels: feature

#195 feat(snippet): add component & doc
  docs/en-us/components/note.md
  docs/en-us/components/snippet.md
  docs/examples/button/icon.vue
  docs/examples/snippet/basic.vue
  docs/examples/snippet/filled.vue
  docs/examples/snippet/multiple.vue
  docs/examples/snippet/type.vue
  docs/examples/snippet/width.vue
  docs/examples/snippet/without-copy.vue
  docs/zh-cn/components/snippet.md
  docs/zh-cn/components/user.md
  package.json
  packages/checkbox/checkbox.styl
  packages/checkbox/checkbox.vue
  packages/collapse/collapse-item.vue
  packages/files/files-icon.vue
  packages/index.js
  packages/select/down-icon.vue
  packages/select/select.vue
  packages/snippet/index.js
  packages/snippet/snippet.styl
  packages/snippet/snippet.vue
  packages/utils/clipboard.js
  packages/utils/index.js
  src/components/examples/arrow-icon.vue
  src/components/examples/code.vue
  yarn.lock
Labels: docs, feature
